import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/app/components/rootlayout/Header";
import {bg} from "@/app/colos";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={`${inter.className} bg-[#0F131B]`}>
      <Header />
      {children}
      </body>
    </html>
  )
}
